<td class="calendar-time-col" style="width: 70px;">
    <?= $this->calendarTimeTable($this->timeStart, $this->timeEnd, $this->timeBlock) ?>
</td>

<?php

$reservations = $this->get('reservations');
$events = $this->get('events');

$reservationsForColPlugin = $this->plugin('CalendarReservationsForCol');
$reservationsCleanupPlugin = $this->plugin('CalendarReservationsCleanup');

$eventsForColPlugin = $this->plugin('CalendarEventsForCol');
$eventsCleanupPlugin = $this->plugin('CalendarEventsCleanup');

/* Loop through day cols */

$walkingDate = clone $this->dateStart;
$walkingIndex = 0;

while ($walkingDate <= $this->dateEnd) {
    if (in_array($walkingDate->format($this->t('Y-m-d')), $this->dayExceptions) ||
        in_array($this->t($walkingDate->format('l')), $this->dayExceptions)) {

        if (! in_array($walkingDate->format($this->t('Y-m-d')), $this->dayExceptionsExceptions)) {
            $walkingDate->modify('+1 day');
            $walkingIndex++;
            continue;
        }
    }

    echo sprintf('<td class="calendar-date-col %s">',
        ($walkingIndex > 0 ? 'responsive-pass-' . (max(1, 5 - $walkingIndex)) : ''));

    echo '<table class="calendar-date-table full-width">';

    echo $this->calendarDateRow($walkingDate, $this->squaresCount);
    echo $this->calendarSquareRow($this->squares, $this->squaresCount);

    /* Loop through time rows */
    $output = array();
    $coljoin = array();
    $row = 0;
    /* pass 1 collect all cells */
    for ($walkingTime = $this->timeStart; $walkingTime < $this->timeEnd; $walkingTime += $this->timeBlock) {
        $walkingDate->modify('+' . $walkingTime . ' sec');

        $reservationsForCol = $reservationsForColPlugin($reservations, $walkingDate, $walkingTime, $this->timeBlock);
        $eventsForCol = $eventsForColPlugin($events, $walkingDate, $walkingTime, $this->timeBlock);

        /* Loop through square cells */
        $idx = 0;
        foreach ($this->squares as $square) {
            $cell = $this->calendarCellLogic($walkingDate, $walkingTime, $this->timeBlock, $this->dateNow,
                $square, $this->user, $reservationsForCol, $eventsForCol);

            $matches = null;
            $key = null;
            preg_match('/cc-group-\d*/', $cell, $matches);
            if ($matches) {
                //echo $matches[0] . '<br>';
                $key = $matches[0];
            }

            $coljoin[$row][$idx] = $key;
            $output[$row][$idx] = $cell;
            $idx += 1;
        }

        $walkingDate->setTime(0, 0, 0);
        $row += 1;
    }

    /* pass 1 output and join cells */
    $collect = array();
    for ($r = 0; $r < $row; $r += 1) {
        echo '<tr class="calendar-core-row">';
        $idx = 0;
        foreach ($this->squares as $square) {
            $key = $coljoin[$r][$idx];
            $cell = $output[$r][$idx];
            if ($key == null) {
            } else if ($r > 0 && $collect[$idx] == $key) {
                $cell = '';
            } else {
                // find the cells to merge
                $cellCount = 1;
                for ($rr = $r + 1; $rr < $row; $rr += 1) {
                    if ($coljoin[$rr][$idx] == $key) {
                        $cellCount += 1;
                    } else {
                        break;
                    }
                }
                $cell = str_replace('<td>', '<td rowspan="'.$cellCount.'">', $cell);
            }
            $collect[$idx] = $key;
            echo $cell;
            $idx += 1;
        }
        echo '</tr>';
    }

    $reservationsCleanupPlugin($reservations, $walkingDate);
    $eventsCleanupPlugin($events, $walkingDate);

    echo $this->calendarSquareRow($this->squares, $this->squaresCount, 'no-print');
    echo $this->calendarDateRow($walkingDate, $this->squaresCount, 'no-print');

    echo '</table>';

    echo '</td>';

    $walkingDate->modify('+1 day');
    $walkingIndex++;
}
